//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmissionsService.WebServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransferData", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TransferData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string valueUuidField;
        
        private int timestampStartField;
        
        private int timestampEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string valueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string parameterUuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string unitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sensorUuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sourceUuidField;
        
        private int pnivField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string valueUuid {
            get {
                return this.valueUuidField;
            }
            set {
                if ((object.ReferenceEquals(this.valueUuidField, value) != true)) {
                    this.valueUuidField = value;
                    this.RaisePropertyChanged("valueUuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int timestampStart {
            get {
                return this.timestampStartField;
            }
            set {
                if ((this.timestampStartField.Equals(value) != true)) {
                    this.timestampStartField = value;
                    this.RaisePropertyChanged("timestampStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int timestampEnd {
            get {
                return this.timestampEndField;
            }
            set {
                if ((this.timestampEndField.Equals(value) != true)) {
                    this.timestampEndField = value;
                    this.RaisePropertyChanged("timestampEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                if ((object.ReferenceEquals(this.valueField, value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string parameterUuid {
            get {
                return this.parameterUuidField;
            }
            set {
                if ((object.ReferenceEquals(this.parameterUuidField, value) != true)) {
                    this.parameterUuidField = value;
                    this.RaisePropertyChanged("parameterUuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string unit {
            get {
                return this.unitField;
            }
            set {
                if ((object.ReferenceEquals(this.unitField, value) != true)) {
                    this.unitField = value;
                    this.RaisePropertyChanged("unit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string sensorUuid {
            get {
                return this.sensorUuidField;
            }
            set {
                if ((object.ReferenceEquals(this.sensorUuidField, value) != true)) {
                    this.sensorUuidField = value;
                    this.RaisePropertyChanged("sensorUuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string state {
            get {
                return this.stateField;
            }
            set {
                if ((object.ReferenceEquals(this.stateField, value) != true)) {
                    this.stateField = value;
                    this.RaisePropertyChanged("state");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string sourceUuid {
            get {
                return this.sourceUuidField;
            }
            set {
                if ((object.ReferenceEquals(this.sourceUuidField, value) != true)) {
                    this.sourceUuidField = value;
                    this.RaisePropertyChanged("sourceUuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int pniv {
            get {
                return this.pnivField;
            }
            set {
                if ((this.pnivField.Equals(value) != true)) {
                    this.pnivField = value;
                    this.RaisePropertyChanged("pniv");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServiceReference.EmissionsWebServiceSoap")]
    public interface EmissionsWebServiceSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем data из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadData", ReplyAction="*")]
        EmissionsService.WebServiceReference.UploadDataResponse UploadData(EmissionsService.WebServiceReference.UploadDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadData", ReplyAction="*")]
        System.Threading.Tasks.Task<EmissionsService.WebServiceReference.UploadDataResponse> UploadDataAsync(EmissionsService.WebServiceReference.UploadDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadData", Namespace="http://tempuri.org/", Order=0)]
        public EmissionsService.WebServiceReference.UploadDataRequestBody Body;
        
        public UploadDataRequest() {
        }
        
        public UploadDataRequest(EmissionsService.WebServiceReference.UploadDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EmissionsService.WebServiceReference.TransferData[] data;
        
        public UploadDataRequestBody() {
        }
        
        public UploadDataRequestBody(EmissionsService.WebServiceReference.TransferData[] data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public EmissionsService.WebServiceReference.UploadDataResponseBody Body;
        
        public UploadDataResponse() {
        }
        
        public UploadDataResponse(EmissionsService.WebServiceReference.UploadDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UploadDataResponseBody {
        
        public UploadDataResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmissionsWebServiceSoapChannel : EmissionsService.WebServiceReference.EmissionsWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmissionsWebServiceSoapClient : System.ServiceModel.ClientBase<EmissionsService.WebServiceReference.EmissionsWebServiceSoap>, EmissionsService.WebServiceReference.EmissionsWebServiceSoap {
        
        public EmissionsWebServiceSoapClient() {
        }
        
        public EmissionsWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmissionsWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmissionsWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmissionsWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmissionsService.WebServiceReference.UploadDataResponse EmissionsService.WebServiceReference.EmissionsWebServiceSoap.UploadData(EmissionsService.WebServiceReference.UploadDataRequest request) {
            return base.Channel.UploadData(request);
        }
        
        public void UploadData(EmissionsService.WebServiceReference.TransferData[] data) {
            EmissionsService.WebServiceReference.UploadDataRequest inValue = new EmissionsService.WebServiceReference.UploadDataRequest();
            inValue.Body = new EmissionsService.WebServiceReference.UploadDataRequestBody();
            inValue.Body.data = data;
            EmissionsService.WebServiceReference.UploadDataResponse retVal = ((EmissionsService.WebServiceReference.EmissionsWebServiceSoap)(this)).UploadData(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmissionsService.WebServiceReference.UploadDataResponse> EmissionsService.WebServiceReference.EmissionsWebServiceSoap.UploadDataAsync(EmissionsService.WebServiceReference.UploadDataRequest request) {
            return base.Channel.UploadDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmissionsService.WebServiceReference.UploadDataResponse> UploadDataAsync(EmissionsService.WebServiceReference.TransferData[] data) {
            EmissionsService.WebServiceReference.UploadDataRequest inValue = new EmissionsService.WebServiceReference.UploadDataRequest();
            inValue.Body = new EmissionsService.WebServiceReference.UploadDataRequestBody();
            inValue.Body.data = data;
            return ((EmissionsService.WebServiceReference.EmissionsWebServiceSoap)(this)).UploadDataAsync(inValue);
        }
    }
}
