// <auto-generated />
namespace server.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class new_tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new_tables));
        
        string IMigrationMetadata.Id
        {
            get { return "202001141512253_new_tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
