//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bmstu.IU6.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accidents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accidents()
        {
            this.Accidents1 = new HashSet<Accidents>();
        }
    
        public System.Guid ID { get; set; }
        public string Post { get; set; }
        public string Description { get; set; }
        public string UserName { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<System.Guid> AType_ID { get; set; }
        public Nullable<System.Guid> NextVersion_ID { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public int Plan { get; set; }
        public int Fact { get; set; }
        public int PlanFact { get; set; }
        public Nullable<System.Guid> BEvent_ID { get; set; }
    
        public virtual AccidentClasses AccidentClasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accidents> Accidents1 { get; set; }
        public virtual Accidents Accidents2 { get; set; }
        public virtual ButtonEvents ButtonEvents { get; set; }
    }
}
