//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bmstu.IU6.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ButtonSnapshots
    {
        public System.Guid ID { get; set; }
        public int BType { get; set; }
        public int Side { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<System.Guid> Post_ID { get; set; }
        public int Counter { get; set; }
    
        public virtual PostSnapshots PostSnapshots { get; set; }
    }
}
