//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bmstu.IU6.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommandMessages
    {
        public System.Guid ID { get; set; }
        public int CType { get; set; }
        public string Text { get; set; }
        public bool State { get; set; }
        public string UserName { get; set; }
        public System.DateTime TimeStamp { get; set; }
    }
}
