//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bmstu.IU6.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConveyorMatrices
    {
        public System.Guid ID { get; set; }
        public int Sensors { get; set; }
        public int State { get; set; }
        public int NextState { get; set; }
    }
}
