//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bmstu.IU6.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaPlayerStatus
    {
        public System.Guid ID { get; set; }
        public int State { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public System.Guid Player_ID { get; set; }
        public int Status { get; set; }
        public string UserName { get; set; }
        public int IPState { get; set; }
    
        public virtual MediaPlayers MediaPlayers { get; set; }
        public virtual MediaPlayers MediaPlayers1 { get; set; }
    }
}
