//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bmstu.IU6.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plans
    {
        public System.Guid ID { get; set; }
        public int PType { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public int PlanCount { get; set; }
        public int FactCount { get; set; }
        public bool Started { get; set; }
        public bool Finished { get; set; }
    }
}
