//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bmstu.IU6.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostSnapshots
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PostSnapshots()
        {
            this.ButtonSnapshots = new HashSet<ButtonSnapshots>();
        }
    
        public System.Guid ID { get; set; }
        public int Post { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public int Support { get; set; }
        public string VIN { get; set; }
        public int TType { get; set; }
        public Nullable<System.Guid> AType_ID { get; set; }
    
        public virtual AccidentClasses AccidentClasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ButtonSnapshots> ButtonSnapshots { get; set; }
    }
}
